name: photo_manager_example
description: Demonstrates how to use the photo_manager plugin.
publish_to: none

environment:
  sdk: ">=2.19.0"
  flutter: ">=3.7.0"

dependencies:
  flutter:
    sdk: flutter

  photo_manager: # override
  photo_manager_image_provider: ^2.1.1

  http: ">=0.13.6 <2.0.0"
  oktoast: ^3.1.0
  path_provider: ^2.0.5
  provider: ^6.0.0
  url_launcher: ^6.1.10
  video_player: ^2.1.14

dev_dependencies:
  flutter_lints: any
  flutter_test:
    sdk: flutter
  test: any

flutter:
  uses-material-design: true

dependency_overrides:
  photo_manager:
    path: ../
