name: photo_manager_example
description: Demonstrates how to use the photo_manager plugin.
version: 3.0.0+26
publish_to: none

environment:
  sdk: ">=2.13.0 <3.0.0"
  flutter: ">=2.2.0"

dependencies:
  flutter:
    sdk: flutter

  http: ^1.1.0
  oktoast: ^3.1.0
  path_provider: ^2.0.5
  photo_manager: ^3.0.0-dev.1
  provider: ^6.0.0
  url_launcher: ^6.1.10
  video_player: ^2.1.14
  photo_manager_image_provider: ^1.1.0 # if you use the flutter 3.14.0 or higher, you can use the version ^2.1.0
  # photo_manager_image_provider: ^2.1.0

dev_dependencies:
  flutter_lints: any
  flutter_test:
    sdk: flutter
  test: any

flutter:
  uses-material-design: true

dependency_overrides:
  photo_manager:
    path: ../
