name: photo_manager
description: A Flutter plugin that provides assets abstraction management APIs on Android, iOS, and macOS.
repository: https://github.com/fluttercandies/flutter_photo_manager
version: 2.8.0

environment:
  sdk: ">=2.13.0 <3.0.0"
  flutter: ">=2.2.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: any
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.fluttercandies.photo_manager
        pluginClass: PhotoManagerPlugin
      ios:
        pluginClass: PhotoManagerPlugin
      macos:
        pluginClass: PhotoManagerPlugin
