name: photo_manager_example_ohos
description: Demonstrates how to use the photo_manager plugin.
version: 3.0.0+26
publish_to: none

environment:
  sdk: ^2.19.0
  flutter: ">=3.7.12"

dependencies:
  flutter:
    sdk: flutter

  http: ^1.1.0
  oktoast: ^3.1.0
  path_provider: ^2.0.5
  photo_manager: ^3.0.0
  provider: ^6.0.0
  url_launcher: ^6.1.10
  video_player: ^2.1.14
  # photo_manager_image_provider: ^1.1.0 # if you use the flutter 3.14.0 or higher, you can use the version ^2.1.0
  photo_manager_image_provider: ^2.1.0
  path_provider_ohos:
     git:
       url: https://gitee.com/openharmony-sig/flutter_packages.git
       path: packages/path_provider/path_provider_ohos
  photo_manager_example:
    path: ../example     
dev_dependencies:
  flutter_lints: 2.0.3
  flutter_test:
    sdk: flutter
  test: any

flutter:
  uses-material-design: true

dependency_overrides:
  photo_manager:
    path: ../
  photo_manager_image_provider: 1.1.1
  http: 0.13.6
  flutter_lints: 2.0.3